site_name: co2tracker
site_description: Co2Tracker for hackathon.
repo_url: https://github.com/migomi3/co2tracker-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/migomi3">migomi3</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
